catalog/urls.py
from django.urls import path

from catalog.views import (
    index, LiteraryFormatListView, BookListView, BookDetailView,
    test_session_view, LiteraryFormatCreateView, LiteraryFormatUpdateView,
    LiteraryFormatDeleteView, AuthorListView, AuthorDetailView,
    AuthorCreateView, BookCreateView, BookUpdateView
)

urlpatterns = [
    path("", index, name="index"),
    path("test-sessions/", test_session_view, name="test-session"),

    path(
        "literary-formats/",
        LiteraryFormatListView.as_view(),
        name="literary_format_list"
    ),
    path(
        "literary-formats/create/",
        LiteraryFormatCreateView.as_view(),
        name="literary-format-create"
    ),
    path(
        "literary-formats/<int:pk>/update/",
        LiteraryFormatUpdateView.as_view(),
        name="literary-format-update"
    ),
    path(
        "literary-formats/<int:pk>/delete/",
        LiteraryFormatDeleteView.as_view(),
        name="literary-format-delete"
    ),

    path(
        "books/",
        BookListView.as_view(),
        name="book-list",
    ),
    path(
        "books/<int:pk>/",
        BookDetailView.as_view(),
        name="book-detail",
    ),
    path(
        "books/create",
        BookCreateView.as_view(),
        name="book-create",
    ),
    path(
        "books/<int:pk>/update",
        BookUpdateView.as_view(),
        name="book-update",
    ),

    path("authors/", AuthorListView.as_view(), name="author-list"),
    path(
        "authors/<int:pk>/",
        AuthorDetailView.as_view(),
        name="author-detail",
    ),
    path("authors/create", AuthorCreateView.as_view(), name="author-create"),
]

app_name = "catalog"

core/urls.py
from django.urls import path
from core.views import PersonListView, PersonCreateView


app_name = "core"

urlpatterns = [
    path("people/", PersonListView.as_view(), name="person-list"),
    path("people/create/", PersonCreateView.as_view(), name="person-create"),
]

library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path("hello-world/<int:unique_number>/", hello_world),
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("core.urls", namespace="core")),

    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: {{ user.username }}</li>
    <li class="list-group-item"><a href="{% url 'logout' %}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}">Login</a></li>
  {% endif %}
  <br>

  <li class="list-group-item"><a href="{% url 'catalog:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:author-list' %}">All authors</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:book-list' %}">All books</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:literary_format_list' %}">All literary formats</a></li>
</ul>