catalog/urls.py
from django.urls import path

from catalog.views import (
    index, LiteraryFormatListView, BookListView, BookDetailView,
    test_session_view, LiteraryFormatCreateView, LiteraryFormatUpdateView,
    LiteraryFormatDeleteView, AuthorListView, AuthorDetailView,
    AuthorCreateView, BookCreateView, BookUpdateView
)

urlpatterns = [
    path("", index, name="index"),
    path("test-sessions/", test_session_view, name="test-session"),

    path(
        "literary-formats/",
        LiteraryFormatListView.as_view(),
        name="literary_format_list"
    ),
    path(
        "literary-formats/create/",
        LiteraryFormatCreateView.as_view(),
        name="literary-format-create"
    ),
    path(
        "literary-formats/<int:pk>/update/",
        LiteraryFormatUpdateView.as_view(),
        name="literary-format-update"
    ),
    path(
        "literary-formats/<int:pk>/delete/",
        LiteraryFormatDeleteView.as_view(),
        name="literary-format-delete"
    ),

    path(
        "books/",
        BookListView.as_view(),
        name="book-list",
    ),
    path(
        "books/<int:pk>/",
        BookDetailView.as_view(),
        name="book-detail",
    ),
    path(
        "books/create",
        BookCreateView.as_view(),
        name="book-create",
    ),
    path(
        "books/<int:pk>/update",
        BookUpdateView.as_view(),
        name="book-update",
    ),

    path("authors/", AuthorListView.as_view(), name="author-list"),
    path(
        "authors/<int:pk>/",
        AuthorDetailView.as_view(),
        name="author-detail",
    ),
    path("authors/create", AuthorCreateView.as_view(), name="author-create"),
]

app_name = "catalog"

core/urls.py
from django.urls import path
from core.views import PersonListView, PersonCreateView


app_name = "core"

urlpatterns = [
    path("people/", PersonListView.as_view(), name="person-list"),
    path("people/create/", PersonCreateView.as_view(), name="person-create"),
]

library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    # path("hello-world/<int:unique_number>/", hello_world),
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("core.urls", namespace="core")),

    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class LiteraryFormat(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    format = models.ForeignKey(
        to=LiteraryFormat,
        on_delete=models.CASCADE,
        related_name="books"
    )
    authors = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL,
        related_name="books",
    )

    class Meta:
        ordering = ["title"]

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.title} (price: {self.price}, " \
               f"format: {self.format.name})"

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from catalog.models import Author, Book


class AuthorCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Author
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "pseudonym")


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = Book
        fields = "__all__"


class BookSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255, required=False, label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title..."})
    )

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from catalog.forms import AuthorCreationForm, BookForm, BookSearchForm
from catalog.models import Book, Author, LiteraryFormat


# def hello_world(request, unique_number):
#     print(request.method)
#     print(request.GET)
#     now = datetime.datetime.now()
#     return HttpResponse(
#         "<html>"
#         "<h1>Hello, world!</h1>"
#         f"<h2>Current moment: {now}</h2>"
#         f"<h2>Current moment: {unique_number}</h2>"
#         "</html>"
#     )


@login_required
def index(request):
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_literary_formats = LiteraryFormat.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_authors": num_authors,
        "num_literary_formats": num_literary_formats,
        "num_visits": num_visits + 1
    }

    return render(request, "catalog/index.html", context=context)


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_format_list"


# def literary_format_list_view(request):
#     literary_format_list = LiteraryFormat.objects.all()
#
#     context = {
#         "literary_format_list": literary_format_list,
#     }
#
#     return render(
#         request, "catalog/literary_format_list.html", context=context
#     )


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    queryset = Book.objects.all().select_related("format")
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = BookSearchForm(initial={
            "title": title
        })

        return context

    def get_queryset(self):
        # title = self.request.GET.get("title")
        form = BookSearchForm(self.request.GET)

        # if title:
        #     return self.queryset.filter(title__icontains=title)

        if form.is_valid():
            return self.queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )

        return self.queryset


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    form_class = BookForm


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm


# def book_detail_view(request, pk):
#     try:
#         book = Book.objects.get(id=pk)
#     except Book.DoesNotExist:
#         raise Http404("Book does not exist")
#
#     context = {
#         "book": book,
#     }
#
#     return render(request, "catalog/book_detail.html", context=context)


def test_session_view(request):
    request.session["book"] = "Test session book"
    return render(request, "catalog/test-sessions.html")


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary_format_list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary_format_list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = LiteraryFormat
    success_url = reverse_lazy("catalog:literary_format_list")
    template_name = "catalog/literary_format_confirm_delete.html"


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 2


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Author
    form_class = AuthorCreationForm

    def get_success_url(self):
        return reverse("catalog:author-detail", kwargs={'pk': self.object.pk})

templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Author: {{ author.username }}</h1>
  <p><strong>Full name: </strong>{{ author.first_name }} {{ author.last_name }}</p>

  <div class="ml-3">
    <h3>Books: </h3>

    {% for book in author.books.all %}
      <hr>
      <p class="text-muted"><strong>Id:</strong>{{ book.id }}</p>
      <p> <strong>Book title:</strong> {{ book.title }} </p>
      <p> <strong>Book format:</strong> {{ book.format }} </p>
    {% empty %}
      <p>No books!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/author_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create Author</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Author List
    <a href="{% url 'catalog:author-create' %}">Create</a>
  </h1>

  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          <a href="{% url 'catalog:author-detail' pk=author.id %}">{{ author.username }}</a>
          ({{ author.first_name }} {{ author.last_name }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no authors yet</p>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Title: {{ book.title }}
    <a href="{% url 'catalog:book-update' pk=book.id%}">Edit</a>
  </h1>
  <p><strong>Price: </strong>{{ book.price }}</p>
  <p><strong>Format: </strong>{{ book.format.name }}</p>

  <div class="ml-3">
    <h3>Authors</h3>

    {% for author in book.authors.all %}
      <hr>
      <p class="text-muted"><strong>Id:</strong>{{ author.id }}</p>
      <p>
        <strong>Full name:</strong>
        {{ author.first_name }} {{ author.last_name }}
        {% if author.pseudonym %}({{ author.pseudonym }}){% endif %}
      </p>
    {% empty %}
      <p>No authors!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/book_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Book</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Book List
    <a href="{% url 'catalog:book-create' %}">Create</a>
  </h1>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input class="btn btn-light" type="submit" value="🔎">
  </form>

  <br>

  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{% url 'catalog:book-detail' pk=book.id %}">{{ book.title }}</a>
          (price: {{ book.price }}, format: {{ book.format.name }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books in library</p>
  {% endif %}
{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}

{% block title %}
  <title>Home page</title>
{% endblock %}

{% block content %}
  <h1>Library Home</h1>
  <p>Welcome to the Greatest Library</p>
  <h2>Library content:</h2>

  <ul>
    <li>Num books: {{ num_books }}</li>
    <li>Num authors: {{ num_authors }}</li>
    <li>Num literary formats: {{ num_literary_formats }}</li>
  </ul>

  <p>
    You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}
  </p>
{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Literary Format</h1>

  <p>Are you sure you want to delete the literary format: {{ literaryformat }}</p>
  <p><i>All books will be deleted as well</i></p>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Yes, delete">
  </form>

{% endblock %}

templates/catalog/literary_format_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Literary Format</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/literary_format_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Literary Format List
    <a href="{% url 'catalog:literary-format-create' %}">Create</a>
  </h1>
  {% if literary_format_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for literary_format in literary_format_list %}
        <tr>
          <td>{{ literary_format.id }}</td>
          <td>{{ literary_format.name }}</td>
          <td>
            <a href="{% url 'catalog:literary-format-update' pk=literary_format.id %}">Update</a>
          </td>
          <td>
            <a href="{% url 'catalog:literary-format-delete' pk=literary_format.id %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no literary formats in library</p>
  {% endif %}
{% endblock %}

templates/catalog/test-sessions.html
{% extends "base.html" %}

{% block content %}
  <h1>Test Session</h1>
{% endblock %}